imports:
    - { resource: ../../Resources/config/config.yml }
    - { resource: security.yml }

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]

cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 20
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.content

# Debug in php and twig
raul_fraile_ladybug:
    array_max_nesting_level: 9 # maximum depth of dump in arrays
    object_max_nesting_level: 3 # maximum depth of dump in objects
    expanded: false # true to expand all the variables tree by default
    silenced: false # true to ignore all ladybug calls
