imports:
    - { resource: ../../Resources/config/config.yml }
    - { resource: security.yml }

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]

cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            sulu_product.product_router: 50
            cmf_routing.dynamic_router: 25
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.portal
