security:
    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: plaintext

    providers:
        sulu:
            entity:
                class: SuluSecurityBundle:User
                property: username

    access_control:
        - { path: ^/, roles: ROLE_USER }

    firewalls:
        sulu:
            pattern: (^/admin)|(^/security/login_check)|(^/security/logout)
            form_login:
                login_path: sulu_security.login
                check_path: sulu_security.login_check
            logout:
                path: /security/logout
                target: /admin
