security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    daniel:  { password: daniel, roles: [ 'ROLE_ADMIN' ] }

    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    firewalls:
        sulu:
            pattern: (^/admin)|(^/security/login_check)|(^/security/logout)
            form_login:
                login_path: sulu_security.login
                check_path: sulu_security.login_check
            logout:
                path: /security/logout
                target: /admin
